### ISSUE TITLE
На странице с графиками сделать вывод по умолчанию

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Zapravka#10]
Нужно сделать, чтобы по умолчанию при выборе заправки выводился график за последнюю неделю "Объём от времени". Соответственно в окошках с датами выводить :
  по "текущую дату"
  с  "минус 7 дней от текущей даты"

**Comment by AlekseySmorshchok** [comment]
сделано

**Comment by GloomlySeth** [comment]
а можно сделать так, чтобы график обновлялся не только после перестановки птички, а ещё и после смены интервала времени?

**Comment by AlekseySmorshchok** [comment]
можно сделаю

**Comment by AlekseySmorshchok** [comment]
сделано.
