### ISSUE TITLE
Сделать загловки у страниц

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Zapravka#11]
Как в файлах прототипов

**Comment by AlekseySmorshchok** [comment]
сделано

**Comment by GloomlySeth** [comment]
Но не обновлено? 
не наблюдаю через браузер...

**Comment by AlekseySmorshchok** [comment]
не обновлено.на главную стр, когда только дерево видно вешать какой нить заголовок?

**Comment by GloomlySeth** [comment]
Давай напишем: "Мониторинг АЗС"

**Comment by AlekseySmorshchok** [comment]
Просто мониторинг АЗС и пустота. или этот заголовок в самом дереве?

**Comment by AlekseySmorshchok** [comment]
сделал
