### ISSUE TITLE
Сохранять настройки интервала времени при переключениях АЗС

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Zapravka#13]
При смене АЗС оставлять уже установленный интервал времени для графиков .

**Comment by AlekseySmorshchok** [comment]
Единственный вариант в текущей версии программы это сохранять данные в браузере, но тогда вопрос когда их чистить?

**Comment by GloomlySeth** [comment]
дай варианты. Как можно сделать.

**Comment by AlekseySmorshchok** [comment]
ну например добавлять еще поле дату сохранения параметров. И проверять, если день прошел то чистить

**Comment by AlekseySmorshchok** [comment]
ну или там 2ч

**Comment by GloomlySeth** [comment]
по идее сохранение нужно только на время сессии, потом можно обнулять и приводить к настройкам по умолчанию. 
+ можно сделать по времени - через 2 часа приводить к настройкам по умолчанию, если пользователь ничего не кликал.

**Comment by AlekseySmorshchok** [comment]
сохраняется до перезагрузки страницы, напишу как залью
