### ISSUE TITLE
Правки к странице с настройками

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Zapravka#4]
![image](https://user-images.githubusercontent.com/18662965/49492266-a860bf00-f868-11e8-8078-47502457a806.png)

**Comment by AlekseySmorshchok** [comment]
сделано

**Comment by GloomlySeth** [comment]
Я понял как ты сделал. Повторяешь введенное значение полей IP и Port
Вопрос. Что будет если пользователь изменит  IP или Port  для другого резервуара?  Случайно или по глупости?

**Comment by AlekseySmorshchok** [comment]
немного не так делаю. я просто не стираю значения этих полей после добавление. Если изменит, то новые данные полетят в резервуар

**Comment by GloomlySeth** [comment]
будет хреново. Сервак будет искать другой  девайс по новому IP на одной и той же заправке. А девайс на заправке как правило  один.

**Comment by AlekseySmorshchok** [comment]
я могу заблочить эти поля после первого ввода наверно

**Comment by GloomlySeth** [comment]
если так сделаешь, будет очень хорошо

**Comment by AlekseySmorshchok** [comment]
сделано

**Comment by GloomlySeth** [comment]
Согласен сделано. Но теперь я заметил кривость:
шапку в таблице нужно оторвать от содержимого. Иначе криво отображается
![image](https://user-images.githubusercontent.com/18662965/49831923-404d3400-fda6-11e8-9891-a65b57e3b632.png)

Или это тоже из-за браузера

**Comment by AlekseySmorshchok** [comment]
сделаю завтра все страницу нормально
