### ISSUE TITLE
Добавить адрес на index.html

### ISSUE THREAD

**Issue by PashaSmurf** [GloomlySeth/Zapravka#5]
Добавить адрес на index.html

**Comment by GloomlySeth** [comment]
Это кому?

**Comment by PashaSmurf** [comment]
Лехе)


>Пятница,  7 декабря 2018, 18:51 +03:00 от GloomlySeth <notifications@github.com>:
>
>Это кому?
>—
>You are receiving this because you were assigned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Павел Ляховский

**Comment by GloomlySeth** [comment]
тогда птичку нужно ставить в том месте, где не скрине синим подсвечено. Иначе Лёха будет не в курсе, что это ему. И lable хорошо бы назначить. 

![image](https://user-images.githubusercontent.com/18662965/49690990-5bbc0300-fb4a-11e8-8837-0f1d8f2d8a7e.png)

**Comment by AlekseySmorshchok** [comment]
Сделано
