### ISSUE TITLE
Заменить слова при отображении значений точек на графике

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Zapravka#6]
![image](https://user-images.githubusercontent.com/18662965/49690916-835e9b80-fb49-11e8-9a0a-9ef8bb129fe3.png)

На графиках с уровнем топлива - прописываем в этом месте "Уровень"

![image](https://user-images.githubusercontent.com/18662965/49691019-ed2b7500-fb4a-11e8-853b-e058fa9de8c4.png)

**Comment by AlekseySmorshchok** [comment]
сделано

**Comment by GloomlySeth** [comment]
Ещё округление до третьего знака после запятой было бы круто на графике скорости

**Comment by AlekseySmorshchok** [comment]
сделано
